name: docker-build

on:
  pull_request:
    branches:
      - '*'
    paths:
      # If scripts under `targets` directory are modified, the `build-on-target-modify` workflow covers the tests
      - '**Dockerfile'
      - '**.sh'
      - '!targets/**.sh'
  push:
    branches:
      - 'main'
    paths:
      - '**Dockerfile'
      - '**.sh'

jobs:
  da_matrix:
    name: 'Test docker build for data augmentation'
    strategy:
      matrix:
        da_method: ['AFLcem', 'ConcFuzz']
    runs-on: ubuntu-20.04
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-da-${{ matrix.da_method }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-da-${{ matrix.da_method }}

      - name: Docker build
        env:
          DA: ${{ matrix.da_method }}
          TARGET_ID: 'libtiff_cve-2016-10094'
        run: |
          # Wrap `docker build` with `docker buildx build`
          docker() {
            if [ "$1" = "build" ]; then
              args=()
              for arg in "$@"; do
                if [[ $arg != "--no-cache" ]]; then
                  args+=("$arg")
                fi
              done
              command docker buildx build --cache-from "type=local,src=/tmp/.buildx-cache" --cache-to "type=local,dest=/tmp/.buildx-cache-new,mode=max" "${args[@]:1}"
            else
              command docker "$@"
            fi
          }
          export -f docker
          ./data_augmentation/container_build.sh

        # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

  fe_matrix:
    name: 'Test docker build for feature extraction'
    strategy:
      matrix:
        fe_method: ['AuroraFE', 'VulnLocFE']
    runs-on: ubuntu-20.04
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-fe-${{ matrix.fe_method }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-fe-${{ matrix.fe_method }}

      - name: Docker build
        env:
          FE: ${{ matrix.fe_method }}
          TARGET_ID: 'libtiff_cve-2016-10094'
        run: |
          # Wrap `docker build` with `docker buildx build`
          docker() {
            if [ "$1" = "build" ]; then
              args=()
              for arg in "$@"; do
                if [[ $arg != "--no-cache" ]]; then
                  args+=("$arg")
                fi
              done
              command docker buildx build --cache-from "type=local,src=/tmp/.buildx-cache" --cache-to "type=local,dest=/tmp/.buildx-cache-new,mode=max" "${args[@]:1}"
            else
              command docker "$@"
            fi
          }
          export -f docker
          ./feature_extraction/container_build.sh

        # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache